/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import backend.Dictionary;
import backend.DictionaryManagement;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.text.BadLocationException;
import javax.swing.text.Document;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import util.Speaker;

/**
 *
 * @author polyfish
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     * @throws java.io.IOException
     */
    public Interface() throws IOException {
        speakerButton = new javax.swing.JButton();
               System.out.println("Working Directory = " + System.getProperty("user.dir"));

        this.speaker = new Speaker();
        this.speakerButton.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent aEv) {
                speaker.speak(searchBar.getText());
            }
        });
        try {
            speakerButton.setBorder(BorderFactory.createEmptyBorder());
            Image speakerIcon = ImageIO.read(new FileInputStream("resources/speaker.png"));
            this.speakerButton.setIcon(new ImageIcon(speakerIcon));
        } catch (IOException e) {
        }
        
        initComponents();
        dict = new Dictionary();
        DictionaryManagement.insertFromFileAnhViet190K(dict);
        
        word_target_style = new SimpleAttributeSet();
        pronunciation_style = new SimpleAttributeSet();
        explanation_style = new SimpleAttributeSet();
        heading_style = new SimpleAttributeSet();

        
        StyleConstants.setFontSize(word_target_style, 30);
        StyleConstants.setBold(word_target_style, true);
        StyleConstants.setForeground(word_target_style, Color.blue);

        StyleConstants.setFontSize(heading_style, 20);
        StyleConstants.setBold(heading_style, true);

        StyleConstants.setFontSize(pronunciation_style, 15);
        StyleConstants.setForeground(pronunciation_style, Color.green);

        StyleConstants.setFontSize(explanation_style, 15);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addWindow = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        wordTextField = new javax.swing.JTextField();
        pronounciationTextField = new javax.swing.JTextField();
        meaningTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        addFailPopup = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        closeAddFailPopup = new javax.swing.JButton();
        addSuccessfullyPopup = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        closeAddSuccessfullyPopup = new javax.swing.JButton();
        removeWindow = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        removeTargetWordTextField = new javax.swing.JTextField();
        removeWordButton = new javax.swing.JButton();
        removeSuccessfullyPopup = new javax.swing.JDialog();
        jLabel9 = new javax.swing.JLabel();
        closeRemoveSuccessfullyPopup = new javax.swing.JButton();
        removeFailedPopup = new javax.swing.JDialog();
        jLabel10 = new javax.swing.JLabel();
        closeRemoveFailedPopup = new javax.swing.JButton();
        searchPanel = new javax.swing.JPanel();
        searchBar = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        matchingList = new javax.swing.JList<>();
        logo = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        DisplayPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        wordExplainField = new javax.swing.JTextPane();

        addWindow.setTitle("Add new word");
        addWindow.setBounds(new java.awt.Rectangle(0, 0, 537, 321));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel1.setText("Add new word");

        jLabel2.setText("New word:");

        jLabel3.setText("Pronounciation:");

        jLabel4.setText("Meaning:");

        wordTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wordTextFieldActionPerformed(evt);
            }
        });

        jButton1.setText("Add");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addWordFromAddWindow(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitAddWindow(evt);
            }
        });

        javax.swing.GroupLayout addWindowLayout = new javax.swing.GroupLayout(addWindow.getContentPane());
        addWindow.getContentPane().setLayout(addWindowLayout);
        addWindowLayout.setHorizontalGroup(
            addWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addWindowLayout.createSequentialGroup()
                .addGroup(addWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addWindowLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel1))
                    .addGroup(addWindowLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(addWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(41, 41, 41)
                        .addGroup(addWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(meaningTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                            .addComponent(pronounciationTextField)
                            .addComponent(wordTextField)))
                    .addGroup(addWindowLayout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        addWindowLayout.setVerticalGroup(
            addWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addWindowLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGroup(addWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(addWindowLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel2))
                    .addGroup(addWindowLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(wordTextField)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pronounciationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(meaningTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(addWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        addFailPopup.setTitle("Add fail");
        addFailPopup.setBounds(new java.awt.Rectangle(0, 0, 132, 100));
        addFailPopup.setPreferredSize(new java.awt.Dimension(132, 110));

        jLabel5.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel5.setText("Add fail!");

        closeAddFailPopup.setText("Close");
        closeAddFailPopup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeAddFailPopupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addFailPopupLayout = new javax.swing.GroupLayout(addFailPopup.getContentPane());
        addFailPopup.getContentPane().setLayout(addFailPopupLayout);
        addFailPopupLayout.setHorizontalGroup(
            addFailPopupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addFailPopupLayout.createSequentialGroup()
                .addGroup(addFailPopupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addFailPopupLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(closeAddFailPopup))
                    .addGroup(addFailPopupLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel5)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        addFailPopupLayout.setVerticalGroup(
            addFailPopupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addFailPopupLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeAddFailPopup)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        addSuccessfullyPopup.setBounds(new java.awt.Rectangle(0, 0, 500, 60));

        jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel6.setText("Add successfully!");

        closeAddSuccessfullyPopup.setText("Close");
        closeAddSuccessfullyPopup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeAddSuccessfullyPopupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addSuccessfullyPopupLayout = new javax.swing.GroupLayout(addSuccessfullyPopup.getContentPane());
        addSuccessfullyPopup.getContentPane().setLayout(addSuccessfullyPopupLayout);
        addSuccessfullyPopupLayout.setHorizontalGroup(
            addSuccessfullyPopupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addSuccessfullyPopupLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel6)
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addSuccessfullyPopupLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(closeAddSuccessfullyPopup)
                .addGap(98, 98, 98))
        );
        addSuccessfullyPopupLayout.setVerticalGroup(
            addSuccessfullyPopupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addSuccessfullyPopupLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeAddSuccessfullyPopup)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        removeWindow.setTitle("Remove word");
        removeWindow.setBounds(new java.awt.Rectangle(0, 0, 300, 200));

        jLabel7.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel7.setText("Remove word");

        jLabel8.setText("Word:");

        removeTargetWordTextField.setToolTipText("");
        removeTargetWordTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeTargetWordTextFieldActionPerformed(evt);
            }
        });

        removeWordButton.setText("Remove");
        removeWordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeWordButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout removeWindowLayout = new javax.swing.GroupLayout(removeWindow.getContentPane());
        removeWindow.getContentPane().setLayout(removeWindowLayout);
        removeWindowLayout.setHorizontalGroup(
            removeWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removeWindowLayout.createSequentialGroup()
                .addGroup(removeWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(removeWindowLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel7))
                    .addGroup(removeWindowLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(removeTargetWordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(194, 194, 194))
            .addGroup(removeWindowLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(removeWordButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        removeWindowLayout.setVerticalGroup(
            removeWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removeWindowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(removeWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(removeTargetWordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(removeWordButton)
                .addContainerGap(149, Short.MAX_VALUE))
        );

        removeSuccessfullyPopup.setTitle("Remove successfully");
        removeSuccessfullyPopup.setBounds(new java.awt.Rectangle(0, 0, 300, 100));

        jLabel9.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel9.setText("Remove successfully!");

        closeRemoveSuccessfullyPopup.setText("Close");
        closeRemoveSuccessfullyPopup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeRemoveSuccessfullyPopupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout removeSuccessfullyPopupLayout = new javax.swing.GroupLayout(removeSuccessfullyPopup.getContentPane());
        removeSuccessfullyPopup.getContentPane().setLayout(removeSuccessfullyPopupLayout);
        removeSuccessfullyPopupLayout.setHorizontalGroup(
            removeSuccessfullyPopupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, removeSuccessfullyPopupLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(32, 32, 32))
            .addGroup(removeSuccessfullyPopupLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(closeRemoveSuccessfullyPopup)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        removeSuccessfullyPopupLayout.setVerticalGroup(
            removeSuccessfullyPopupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removeSuccessfullyPopupLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeRemoveSuccessfullyPopup)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        removeFailedPopup.setTitle("Remove failed");
        removeFailedPopup.setBounds(new java.awt.Rectangle(0, 0, 300, 120));

        jLabel10.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel10.setText("Remove failed!");

        closeRemoveFailedPopup.setText("Close");
        closeRemoveFailedPopup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeRemoveFailedPopupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout removeFailedPopupLayout = new javax.swing.GroupLayout(removeFailedPopup.getContentPane());
        removeFailedPopup.getContentPane().setLayout(removeFailedPopupLayout);
        removeFailedPopupLayout.setHorizontalGroup(
            removeFailedPopupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removeFailedPopupLayout.createSequentialGroup()
                .addGroup(removeFailedPopupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(removeFailedPopupLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel10))
                    .addGroup(removeFailedPopupLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(closeRemoveFailedPopup)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        removeFailedPopupLayout.setVerticalGroup(
            removeFailedPopupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removeFailedPopupLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(closeRemoveFailedPopup)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        searchBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pressEnterFromSearchBar(evt);
            }
        });
        searchBar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                updateMatchingList(evt);
            }
        });

        searchButton.setIcon(new javax.swing.ImageIcon("/home/polyfish/NetBeansProjects/Dictionary/resources/search.png")); // NOI18N

        matchingList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chooseWordFromMatchingBox(evt);
            }
        });
        matchingList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                selectWordFromMatchingList(evt);
            }
        });
        jScrollPane1.setViewportView(matchingList);

        logo.setIcon(new javax.swing.ImageIcon("/home/polyfish/NetBeansProjects/Dictionary/resources/logo.png")); // NOI18N

        addButton.setText("Add");
        addButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showAddWindow(evt);
            }
        });
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        removeButton.setText("Remove");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchBar, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(searchButton)
                            .addComponent(removeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton))
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(addButton)
                        .addGap(9, 9, 9)
                        .addComponent(removeButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        wordExplainField.setEditable(false);
        jScrollPane3.setViewportView(wordExplainField);

        javax.swing.GroupLayout DisplayPanelLayout = new javax.swing.GroupLayout(DisplayPanel);
        DisplayPanel.setLayout(DisplayPanelLayout);
        DisplayPanelLayout.setHorizontalGroup(
            DisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DisplayPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
                .addContainerGap())
        );
        DisplayPanelLayout.setVerticalGroup(
            DisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DisplayPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(searchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DisplayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(searchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(DisplayPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateMatchingList(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_updateMatchingList
        // TODO add your handling code here:
        String currentText = searchBar.getText();
        
        List<String> matching_words = DictionaryManagement.getPrefixMatchedList(dict, currentText);
        DefaultListModel<String> listModel = new DefaultListModel<>();
        matching_words.forEach(s -> {
            listModel.addElement(s);
        });

        matchingList.setModel(listModel);
    }//GEN-LAST:event_updateMatchingList

    private void pressEnterFromSearchBar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pressEnterFromSearchBar
        // TODO add your handling code here:
        updateWord(searchBar.getText());
    }//GEN-LAST:event_pressEnterFromSearchBar

    private void chooseWordFromMatchingBox(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chooseWordFromMatchingBox
        // TODO add your handling code here:
        updateWord(searchBar.getText());
    }//GEN-LAST:event_chooseWordFromMatchingBox

    private void selectWordFromMatchingList(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_selectWordFromMatchingList
        // TODO add your handling code here:
        String selectedWord = matchingList.getSelectedValue();
        if (selectedWord != null) {
            searchBar.setText(selectedWord);
            updateWord(selectedWord);
        }
    }//GEN-LAST:event_selectWordFromMatchingList

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        // TODO add your handling code here:
        removeWindow.setVisible(true);
    }//GEN-LAST:event_removeButtonActionPerformed

    private void showAddWindow(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showAddWindow
        // TODO add your handling code here:
        addWindow.setVisible(true);
    }//GEN-LAST:event_showAddWindow

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addButtonActionPerformed

    private void wordTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wordTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wordTextFieldActionPerformed

    private void exitAddWindow(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitAddWindow
        // TODO add your handling code here:
        addWindow.dispose();
    }//GEN-LAST:event_exitAddWindow

    private void addWordFromAddWindow(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addWordFromAddWindow
        // TODO add your handling code here:
        String word = wordTextField.getText();
        String pronounciation = pronounciationTextField.getText();
        String meaning = meaningTextField.getText();
        System.out.println(dict.contains(word));
        
        if (!dict.contains(word)) {
            dict.add(word, meaning, pronounciation);
            addSuccessfullyPopup.setVisible(true);
        }
        else {
            addFailPopup.setVisible(true);
        }
    }//GEN-LAST:event_addWordFromAddWindow

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void closeAddFailPopupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeAddFailPopupActionPerformed
        // TODO add your handling code here:
        addFailPopup.dispose();
    }//GEN-LAST:event_closeAddFailPopupActionPerformed

    private void closeAddSuccessfullyPopupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeAddSuccessfullyPopupActionPerformed
        // TODO add your handling code here:
        addSuccessfullyPopup.dispose();
    }//GEN-LAST:event_closeAddSuccessfullyPopupActionPerformed

    private void removeWordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeWordButtonActionPerformed
        // TODO add your handling code here:
        
        String word = removeTargetWordTextField.getText();
        
        if (dict.contains(word)) {
            dict.remove(word);
            removeSuccessfullyPopup.setVisible(true);
        }
        else {
            removeFailedPopup.setVisible(true);
        }
    }//GEN-LAST:event_removeWordButtonActionPerformed

    private void closeRemoveSuccessfullyPopupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeRemoveSuccessfullyPopupActionPerformed
        // TODO add your handling code here:
        removeSuccessfullyPopup.dispose();
    }//GEN-LAST:event_closeRemoveSuccessfullyPopupActionPerformed

    private void closeRemoveFailedPopupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeRemoveFailedPopupActionPerformed
        // TODO add your handling code here:
        removeFailedPopup.dispose();
    }//GEN-LAST:event_closeRemoveFailedPopupActionPerformed

    private void removeTargetWordTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeTargetWordTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeTargetWordTextFieldActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Interface().setVisible(true);
                } catch (IOException e) {
                    
                }
            }
        });
    }
    

    public void updateWord(String word_target) {
        wordExplainField.setText("");
        Document doc = wordExplainField.getStyledDocument();

        String[] word_data = DictionaryManagement.dictionaryLookup(dict, word_target);
        if (word_data == null) {
            wordExplainField.setText(word_target + " not found");
            return;
        }

        String word_explain = word_data[0];
        String word_pronunciation = word_data[1];
        try {
            doc.insertString(doc.getLength(), word_target, word_target_style);
            
            wordExplainField.setCaretPosition(wordExplainField.getDocument().getLength());
            wordExplainField.insertComponent(speakerButton);
            if (!speaker.isAvailable(word_target)) {
                speakerButton.setEnabled(false);
                System.out.println(word_target + " " + "disabled");
            }
            else {
                speakerButton.setEnabled(true);
                System.out.println(word_target + " " + "enabled");
            }
            
            doc.insertString(doc.getLength(), "\n", word_target_style);
            doc.insertString(doc.getLength(), "Pronunciation: ", heading_style);
            doc.insertString(doc.getLength(), word_pronunciation + "\n", pronunciation_style);
            doc.insertString(doc.getLength(), "Meaning:\n", heading_style);
            doc.insertString(doc.getLength(), word_explain, explanation_style);
        } catch (BadLocationException e) {
        }
    }

    // User declaration
    private final Dictionary dict;
    private final SimpleAttributeSet word_target_style;
    private final SimpleAttributeSet pronunciation_style;
    private final SimpleAttributeSet heading_style;
    private final SimpleAttributeSet explanation_style;
    private final Speaker speaker;
    
    private javax.swing.JButton speakerButton;

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DisplayPanel;
    private javax.swing.JButton addButton;
    private javax.swing.JDialog addFailPopup;
    private javax.swing.JDialog addSuccessfullyPopup;
    private javax.swing.JDialog addWindow;
    private javax.swing.JButton closeAddFailPopup;
    private javax.swing.JButton closeAddSuccessfullyPopup;
    private javax.swing.JButton closeRemoveFailedPopup;
    private javax.swing.JButton closeRemoveSuccessfullyPopup;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel logo;
    private javax.swing.JList<String> matchingList;
    private javax.swing.JTextField meaningTextField;
    private javax.swing.JTextField pronounciationTextField;
    private javax.swing.JButton removeButton;
    private javax.swing.JDialog removeFailedPopup;
    private javax.swing.JDialog removeSuccessfullyPopup;
    private javax.swing.JTextField removeTargetWordTextField;
    private javax.swing.JDialog removeWindow;
    private javax.swing.JButton removeWordButton;
    private javax.swing.JTextField searchBar;
    private javax.swing.JButton searchButton;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JTextPane wordExplainField;
    private javax.swing.JTextField wordTextField;
    // End of variables declaration//GEN-END:variables
}
